name: Deploy infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
          terraform_version: ~1.3

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform plan
        run: terraform apply -auto-approve -input=false
